# Numpy: Numerical Python

Numpy is a fundamental package for scientific computations in Python. Numpy stands for Numerical Python and was first created in the year 2005 by Travis Oliphant.

Numpy is a Python library used for working on arrays. In Python we have list datatype object that serves somewhat the same purpose as an array however the key difference is in terms of processing speed. As per a research it was found that an array object is almost 50 times faster than a list datatype object.

The array object in Numpy is called as an "ndarray" object. Numpy also has special functions that widen its scope of usage into the domains of linear algebra, matrices, etc.

Nothing in Python library Numpy is saved until it is assigned a variable. Numpy consists of "multi-dimensional" array objects.

### Importing Numpy library of Python

In [1]:
import numpy as np

### Numpy Array Creation Techniques

###### Empty

In [2]:
a=np.empty(10)

In [3]:
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
b=np.empty((2,3),dtype=int)

In [5]:
print(b)

[[-1587589376       32765 -1587584864]
 [      32765     5439567          69]]


###### Zeros

In [6]:
c=np.zeros(5)

In [7]:
print(c)

[0. 0. 0. 0. 0.]


In [8]:
d=np.zeros((5,5),dtype=int)

In [9]:
print(d)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


###### Ones

In [10]:
e=np.ones(5,dtype=int)

In [11]:
print(e)

[1 1 1 1 1]


In [12]:
f=np.ones((3,2))

In [13]:
print(f)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


###### Eye

In [14]:
g=np.eye(5)

In [15]:
print(g)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
print(g*5)

[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]


In [17]:
print(g+5)

[[6. 5. 5. 5. 5.]
 [5. 6. 5. 5. 5.]
 [5. 5. 6. 5. 5.]
 [5. 5. 5. 6. 5.]
 [5. 5. 5. 5. 6.]]


###### Arange

In [18]:
h=np.arange(1,11)

In [19]:
print(h)

[ 1  2  3  4  5  6  7  8  9 10]


In [20]:
print(h.reshape(2,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [21]:
i=np.arange(1,26).reshape(5,5)

In [22]:
print(i)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


###### Array

In [23]:
j=np.array([1,2,3,4,5])

In [24]:
print(j)

[1 2 3 4 5]


In [25]:
k=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [26]:
print(k)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


###### Linspace

In [27]:
l=np.linspace(0.01,1,100)

In [28]:
print(l.reshape(10,10))

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


### Numpy Multi-Dimensional Array Objects

###### One- Dimensional Array

In [29]:
m=np.array([1,2,3,4,5])

In [30]:
print(m)

[1 2 3 4 5]


In [31]:
n=np.arange(1,21)

In [32]:
print(n)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


###### Two- Dimensional Array

In [33]:
o=np.array([[1,2,3,4],[5,6,7,8]])

In [34]:
print(o)

[[1 2 3 4]
 [5 6 7 8]]


In [35]:
p=np.arange(1,26).reshape(5,5)

In [36]:
print(p)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


### Numpy Array Functions

In [37]:
q=np.arange(1,11).reshape(2,5)
print(q)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [38]:
r=np.arange(11,21).reshape(2,5)
print(r)

[[11 12 13 14 15]
 [16 17 18 19 20]]


In [39]:
q1=np.array([1,2,3,4])
print(q1)

[1 2 3 4]


In [40]:
r1=np.array([5,6,7,8])
print(r1)

[5 6 7 8]


###### Concatenate

For 1-D array objects concatenate function will undertake Hstack and for 2-D array objects concatenate will undertake Vstack

In [41]:
np.concatenate((q,r)) #Array q and r both are 2-D array objects

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [42]:
np.concatenate((q1,r1)) ##Array q1 and r1 both are 1-D array objects

array([1, 2, 3, 4, 5, 6, 7, 8])

###### Hstack or Horizontal stacking

In [43]:
np.hstack((q,r))

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

In [44]:
np.hstack((q1,r1))

array([1, 2, 3, 4, 5, 6, 7, 8])

###### Vstack or Vertical stacking

In [45]:
np.vstack((q,r))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [46]:
np.vstack((q1,r1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

###### Append

In [47]:
np.append(q,r)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [48]:
np.append(q1,r1)

array([1, 2, 3, 4, 5, 6, 7, 8])

###### Insert

In [49]:
np.insert(q1,2,30)

array([ 1,  2, 30,  3,  4])

In [50]:
np.insert(r1,0,100)

array([100,   5,   6,   7,   8])

###### Delete

In [51]:
np.delete(q1,1)

array([1, 3, 4])

In [52]:
np.delete(r1,2)

array([5, 6, 8])

### Numpy Array Methods

###### Type

In [53]:
s=np.array([1,2,3,4,5])

In [54]:
type(s)

numpy.ndarray

###### Shape

In [55]:
t=np.arange(1,11)

In [56]:
np.shape(t)

(10,)

In [57]:
u=np.arange(1,11).reshape(5,2)

In [58]:
np.shape(u)

(5, 2)

###### Size

In [59]:
v=np.arange(1,26).reshape(5,5)

In [60]:
np.size(v)

25

In [61]:
w=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [62]:
np.size(w)

9

###### Reshape

In [63]:
x=np.arange(1,11)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [64]:
x.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [65]:
y=np.linspace(1,10,100)
print(y)

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

In [66]:
y.reshape(20,5)

array([[ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636],
       [ 1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182],
       [ 1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727],
       [ 2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273],
       [ 2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818],
       [ 3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364],
       [ 3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909],
       [ 4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455],
       [ 4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ],
       [ 5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545],
       [ 5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091],
       [ 6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636],
       [ 6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182],
       [ 6.90909091,  7.        ,  7.0

###### Transpose

In [67]:
z=np.arange(1,21).reshape(4,5)
print(z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [68]:
z.transpose()

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [69]:
aa=np.arange(1,11).reshape(5,2)
print(aa)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [70]:
aa.transpose()

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

###### Ndim

In [71]:
ab=np.array([1,2,3,4,5])

In [72]:
np.ndim(ab)

1

In [73]:
ac=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [74]:
np.ndim(ac)

2

### Numpy Array Subset Selection

In case of Numpy array subset selection we deal with a concept called Masking in Numpy.

Numpy offers an in-built Masked Array module called "ma". The masked array function of this module allows us to directly create a masked array in which the elements not satisfying the condition are rendered as False and are hidden from the output and the elements that meet the condition are rendered as True and are presented in the output.

The Subset Selection syntax is as follows:

array_name[row_start:row_stop,col_start:col_stop]

In [75]:
ad=np.arange(1,101).reshape(10,10)
print(ad)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [76]:
ad[1:5,3:6]

array([[14, 15, 16],
       [24, 25, 26],
       [34, 35, 36],
       [44, 45, 46]])

In [77]:
ad[-1:, : ]

array([[ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [78]:
ad[ :3,-2:]

array([[ 9, 10],
       [19, 20],
       [29, 30]])

In [79]:
ad[-5: ,-3: ]

array([[ 58,  59,  60],
       [ 68,  69,  70],
       [ 78,  79,  80],
       [ 88,  89,  90],
       [ 98,  99, 100]])

### Numpy Matrix Level Arithematic Operations

In [80]:
a1=np.array([1,2,3])
print(a1)

[1 2 3]


In [81]:
a2=np.array([4,5,6])
print(a2)

[4 5 6]


In [82]:
a3=np.arange(1,11).reshape(2,5)
print(a3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [83]:
a4=np.arange(11,21).reshape(2,5)
print(a4)

[[11 12 13 14 15]
 [16 17 18 19 20]]


In [84]:
a5=np.arange(1,26).reshape(5,5)
print(a5)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [85]:
a6=np.arange(26,51).reshape(5,5)
print(a6)

[[26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


###### Add

In [86]:
np.add(a1,a2)

array([5, 7, 9])

In [87]:
np.add(a3,a4)

array([[12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [88]:
np.add(a5,a6)

array([[27, 29, 31, 33, 35],
       [37, 39, 41, 43, 45],
       [47, 49, 51, 53, 55],
       [57, 59, 61, 63, 65],
       [67, 69, 71, 73, 75]])

###### Subtract

In [89]:
np.subtract(a2,a1)

array([3, 3, 3])

In [90]:
np.subtract(a4,a3)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [91]:
np.subtract(a6,a5)

array([[25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25]])

###### Multiply

In [92]:
np.multiply(a1,a2)

array([ 4, 10, 18])

In [93]:
np.multiply(a3,a4)

array([[ 11,  24,  39,  56,  75],
       [ 96, 119, 144, 171, 200]])

In [94]:
np.multiply(a5,a6)

array([[  26,   54,   84,  116,  150],
       [ 186,  224,  264,  306,  350],
       [ 396,  444,  494,  546,  600],
       [ 656,  714,  774,  836,  900],
       [ 966, 1034, 1104, 1176, 1250]])

###### Divide

In [95]:
np.divide(a1,a2)

array([0.25, 0.4 , 0.5 ])

In [96]:
np.divide(a3,a4)

array([[0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333],
       [0.375     , 0.41176471, 0.44444444, 0.47368421, 0.5       ]])

In [97]:
np.divide(a5,a6)

array([[0.03846154, 0.07407407, 0.10714286, 0.13793103, 0.16666667],
       [0.19354839, 0.21875   , 0.24242424, 0.26470588, 0.28571429],
       [0.30555556, 0.32432432, 0.34210526, 0.35897436, 0.375     ],
       [0.3902439 , 0.4047619 , 0.41860465, 0.43181818, 0.44444444],
       [0.45652174, 0.46808511, 0.47916667, 0.48979592, 0.5       ]])

###### Remainder

In [98]:
np.remainder(a2,a1) #Element of a2 divided by element of a1 and the remainder so found

array([0, 1, 0], dtype=int32)

In [99]:
np.remainder(a4,a3)

array([[0, 0, 1, 2, 0],
       [4, 3, 2, 1, 0]], dtype=int32)

In [100]:
np.remainder(a6,a5)

array([[ 0,  1,  1,  1,  0],
       [ 1,  4,  1,  7,  5],
       [ 3,  1, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]], dtype=int32)

###### Matmul

In [101]:
np.matmul(a1,a2)

32

In [102]:
np.matmul(a5,a6)

array([[ 590,  605,  620,  635,  650],
       [1490, 1530, 1570, 1610, 1650],
       [2390, 2455, 2520, 2585, 2650],
       [3290, 3380, 3470, 3560, 3650],
       [4190, 4305, 4420, 4535, 4650]])

###### Kron

In [103]:
np.kron(a1,a3)

array([[ 1,  2,  3,  4,  5,  2,  4,  6,  8, 10,  3,  6,  9, 12, 15],
       [ 6,  7,  8,  9, 10, 12, 14, 16, 18, 20, 18, 21, 24, 27, 30]])

In [104]:
np.kron(a3,a6)

array([[ 26,  27,  28,  29,  30,  52,  54,  56,  58,  60,  78,  81,  84,
         87,  90, 104, 108, 112, 116, 120, 130, 135, 140, 145, 150],
       [ 31,  32,  33,  34,  35,  62,  64,  66,  68,  70,  93,  96,  99,
        102, 105, 124, 128, 132, 136, 140, 155, 160, 165, 170, 175],
       [ 36,  37,  38,  39,  40,  72,  74,  76,  78,  80, 108, 111, 114,
        117, 120, 144, 148, 152, 156, 160, 180, 185, 190, 195, 200],
       [ 41,  42,  43,  44,  45,  82,  84,  86,  88,  90, 123, 126, 129,
        132, 135, 164, 168, 172, 176, 180, 205, 210, 215, 220, 225],
       [ 46,  47,  48,  49,  50,  92,  94,  96,  98, 100, 138, 141, 144,
        147, 150, 184, 188, 192, 196, 200, 230, 235, 240, 245, 250],
       [156, 162, 168, 174, 180, 182, 189, 196, 203, 210, 208, 216, 224,
        232, 240, 234, 243, 252, 261, 270, 260, 270, 280, 290, 300],
       [186, 192, 198, 204, 210, 217, 224, 231, 238, 245, 248, 256, 264,
        272, 280, 279, 288, 297, 306, 315, 310, 320, 330, 340, 350],
      

In [105]:
np.kron(a5,a2)

array([[  4,   5,   6,   8,  10,  12,  12,  15,  18,  16,  20,  24,  20,
         25,  30],
       [ 24,  30,  36,  28,  35,  42,  32,  40,  48,  36,  45,  54,  40,
         50,  60],
       [ 44,  55,  66,  48,  60,  72,  52,  65,  78,  56,  70,  84,  60,
         75,  90],
       [ 64,  80,  96,  68,  85, 102,  72,  90, 108,  76,  95, 114,  80,
        100, 120],
       [ 84, 105, 126,  88, 110, 132,  92, 115, 138,  96, 120, 144, 100,
        125, 150]])

In [106]:
np.kron(a2,a3)

array([[ 4,  8, 12, 16, 20,  5, 10, 15, 20, 25,  6, 12, 18, 24, 30],
       [24, 28, 32, 36, 40, 30, 35, 40, 45, 50, 36, 42, 48, 54, 60]])

###### Log

In [107]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [108]:
np.log(a5)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ],
       [2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227],
       [3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582]])

### Numpy Random number selection- Rand and Randn

Random.rand selects random numbers between 0-9 where as random.randn will choose random numbers between -9 and +9

In [109]:
a7=np.random.rand(5)
print(a7)

[0.61510917 0.17894042 0.14046639 0.32105549 0.55299423]


In [110]:
a8=np.random.randn(5)
print(a8)

[-0.79375248  0.22120465 -0.60302289  0.17446123  1.24581609]


### Numpy Matrix Level Statistical Operations

###### Square Root- Sqrt

In [111]:
a9=np.arange(4,41)
print(a9)

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
 28 29 30 31 32 33 34 35 36 37 38 39 40]


In [112]:
np.sqrt(a9)

array([2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712,
       3.        , 3.16227766, 3.31662479, 3.46410162, 3.60555128,
       3.74165739, 3.87298335, 4.        , 4.12310563, 4.24264069,
       4.35889894, 4.47213595, 4.58257569, 4.69041576, 4.79583152,
       4.89897949, 5.        , 5.09901951, 5.19615242, 5.29150262,
       5.38516481, 5.47722558, 5.56776436, 5.65685425, 5.74456265,
       5.83095189, 5.91607978, 6.        , 6.08276253, 6.164414  ,
       6.244998  , 6.32455532])

###### Ceil

In [113]:
a10=np.random.rand(10)
print(a10)

[0.87150279 0.43229345 0.10126567 0.62685158 0.13747437 0.48354873
 0.04442234 0.12313915 0.26326473 0.89948261]


In [114]:
np.ceil(a10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

###### Floor

In [115]:
a11=np.random.randn(5)
print(a11)

[ 0.10799416 -0.96448324  2.64513962  2.79409439 -0.61602745]


In [116]:
np.floor(a11)

array([ 0., -1.,  2.,  2., -1.])

###### IsNaN

In [117]:
a12=np.array([1,2,3,np.nan,5,6,7,8])
print(a12)

[ 1.  2.  3. nan  5.  6.  7.  8.]


In [118]:
np.isnan(a12)

array([False, False, False,  True, False, False, False, False])

###### Mean

In [119]:
a13=np.array([1,2,3,4,5,6,7,8,9,10])
print(a13)

[ 1  2  3  4  5  6  7  8  9 10]


In [120]:
np.mean(a13)

5.5

###### Standard Deviation

In [121]:
a14=np.random.rand(40)
print(a14)

[0.82831335 0.00793648 0.33254295 0.60893082 0.6664146  0.56290113
 0.02967974 0.61875556 0.10328879 0.72729185 0.11521449 0.25636448
 0.31471507 0.15907242 0.93553686 0.10174697 0.06095819 0.4465682
 0.69010088 0.16365058 0.48339863 0.69295088 0.40388875 0.37502311
 0.74373822 0.05202099 0.88760167 0.42347456 0.87625986 0.24639658
 0.79516641 0.70843815 0.73963451 0.26873799 0.47208793 0.86876107
 0.4008481  0.32479209 0.48136196 0.71306393]


In [122]:
np.std(a14)

0.27490306332525755

###### Maximum-Max and Argmax

In [123]:
a15=np.random.randn(20)
print(a15)

[ 0.36610719  0.58358931  0.05902776 -1.05876597  0.87269385 -1.00819253
 -0.17454252 -0.03055388 -0.11911904 -0.46677227  0.17477191  1.78884038
  0.37982505  1.06118813 -2.03117887 -0.47701272 -0.22210696  0.20742466
  0.47843281 -0.43324752]


In [124]:
np.max(a15)

1.7888403776884427

In [125]:
np.argmax(a15) #Argmax returns the index number of the Maximum element

11

###### Sum

In [126]:
a16=np.arange(1,21)
print(a16)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [127]:
np.sum(a16)

210

In [128]:
a17=np.arange(1,26).reshape(5,5)
print(a17)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [129]:
np.sum(a17,axis=0)

array([55, 60, 65, 70, 75])

In [130]:
np.sum(a17,axis=1)

array([ 15,  40,  65,  90, 115])